In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
group_results = pd.read_csv("../System/group_results.csv", index_col=False)
group_results.set_index('group', inplace=True)
group_results

         group  precision    recall  accuracy        f1
0   complexity   0.607499  0.670259  0.665595  0.665953
1    deception   0.568225  0.584052  0.614148  0.600887
2      details   0.594621  0.627155  0.648446  0.639560
3    formality   0.544820  0.538793  0.580922  0.561167
4       humour   0.539505  0.489224  0.572347  0.532239
5  imagination   0.548349  0.553879  0.586281  0.571111
6    vagueness   0.547655  0.614224  0.586281  0.596234

             precision    recall  accuracy        f1
group
complexity    0.607499  0.670259  0.665595  0.665953
deception     0.568225  0.584052  0.614148  0.600887
details       0.594621  0.627155  0.648446  0.639560
formality     0.544820  0.538793  0.580922  0.561167
humour        0.539505  0.489224  0.572347  0.532239
imagination   0.548349  0.553879  0.586281  0.571111
vagueness     0.547655  0.614224  0.586281  0.596234